import = [ "~/.config/alacritty/themes/everforest_dark.toml" ]

live_config_reload = true

[env]
TERM = "xterm-256color"

[window]
dynamic_padding = true
opacity = 0.9

[font]
size = 16

[font.normal]
family = "Iosevka"
style = "Regular"

[font.bold]
family = "Iosevka"
style = "Regular"

[font.italic]
family = "Iosevka"
style = "Italic"

[font.bold_italic]
family = "Iosevka"
style = "Italic"

[scrolling]
history = 10000
multiplier = 10

[colors]
draw_bold_text_with_bright_colors = true

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"
save_to_clipboard = true

[keyboard]
bindings = [
  { key = "N", mods = "Control|Shift", action = "CreateNewWindow" },
]


